### ISSUE TITLE
Can not properly handle a WSDL ( AssertionError: false == true at TypesElement.addChild (wsdl.js:259:5)

### ISSUE THREAD

**Issue by yicheinchang** [vpulim/node-soap#169]
Hi, I am a newbie. Hopefully my first report is an OP.

I tried to use node-soap to access the web service provided by BRENDA.
A complete WRDS is public available at http://www.brenda-enzymes.org/soap2/brenda.wsdl

However, it looks like nood-soap can not properly handle this wsdl. Here is my test script

``` javascript
var soap = require('soap');
var wsdl = 'http://brenda-enzymes.info/soap2/brenda.wsdl';
cl=soap.createClient(wsdl, function(err, client) {
    client.describe();
});
```

And I got the following error

```
AssertionError: false == true
at TypesElement.addChild (node_modules/soap/lib/wsdl.js:259:5)
at Element.endElement (node_modules/soap/lib/wsdl.js:109:20)
at null.<anonymous> (node_modules/soap/lib/wsdl.js:918:13)
at EventEmitter.emit (events.js:95:17)
at Parser.parse (node_modules/soap/node_modules/node-expat/lib/node-expat.js:18:22)
at WSDL._parse (node_modules/soap/lib/wsdl.js:921:12)
at WSDL._fromXML (node_modules/soap/lib/wsdl.js:929:29)
at node_modules/soap/lib/wsdl.js:585:18
at process._tickCallback (node.js:415:13)
```

Don't know why but the XML parser is stuck here

```
<types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="ws.brenda">
        <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
        <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/"/>
    </xsd:schema>
    <xsd:complexType name="ArrayOfIntegers">
        <xsd:complexContent>
            <xsd:restriction base="soapenc:Array">
                <xsd:attribute ref="soapenc:arrayType" wsdl:arrayType="xsd:int[]"/>
            </xsd:restriction>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="ArrayOfStrings">
        <xsd:complexContent>
            <xsd:restriction base="soapenc:Array">
                <xsd:attribute ref="soapenc:arrayType" wsdl:arrayType="xsd:string[]"/>
            </xsd:restriction>
        </xsd:complexContent>
    </xsd:complexType>
```

Thanks for any help.

**Comment by michaelfuzdavines** [comment]
FWIW I ran into both of these problems and discovered that the xml I was requesting had an element that was giving the parser trouble.  The offensive element for me was:

<wsdl:documentation>
Naming convention: tXXX: A type used in a message fXXX: A fault type
/wsdl:documentation>

There were several wsdl:documentation elements with similar syntax.  As a quick workaround I copied the entire xml into a local doc, deleted the documentation elements and had the client read the local file.  Worked for me.
