### ISSUE TITLE
this.element undefined

### ISSUE THREAD

**Issue by louis77** [vpulim/node-soap#318]
With this WSDL:
http://www.tomas.ch/tws220/services/TwsBook20?wsdl

createClient throws this:

```
~/soap/lib/wsdl.js:414
    this.element.targetNSAlias = ns;
                               ^
TypeError: Cannot set property 'targetNSAlias' of undefined
    at MessageElement.postProcess (/Users/louis77/Git/test/node_modules/soap/lib/wsdl.js:414:32)
    at OperationElement.postProcess (/Users/louis77/Git/test/node_modules/soap/lib/wsdl.js:452:13)
    at PortTypeElement.postProcess (/Users/louis77/Git/test/node_modules/soap/lib/wsdl.js:472:11)
    at BindingElement.postProcess (/Users/louis77/Git/test/node_modules/soap/lib/wsdl.js:486:12)
    at ServiceElement.postProcess (/Users/louis77/Git/test/node_modules/soap/lib/wsdl.js:521:15)
    at /Users/louis77/Git/test/node_modules/soap/lib/wsdl.js:693:26
    at /Users/louis77/Git/test/node_modules/soap/lib/wsdl.js:753:7
    at WSDL._processNextInclude (/Users/louis77/Git/test/node_modules/soap/lib/wsdl.js:737:12)
    at null.callback (/Users/louis77/Git/test/node_modules/soap/lib/wsdl.js:752:10)
    at /Users/louis77/Git/test/node_modules/soap/lib/wsdl.js:721:12
```

When I wrap this.element like this
```
if (this.element) {
    this.element.targetNSAlias = ns;
    this.element.targetNamespace = definitions.xmlns[ns];
}
```
createClient() seems to work and I can execute .describe() .

**Comment by jsdevel** [comment]
Closing for lack of activity.
