### ISSUE TITLE
Error parsing WSDL

### ISSUE THREAD

**Issue by giesse** [vpulim/node-soap#46]
Using the following WSDL: https://ics2wstest.ic3.com/commerce/1.x/transactionProcessor/CyberSourceTransaction_1.26.wsdl

I get the following error:

TypeError: Cannot read property 'elements' of undefined
    at [object Object].postProcess (node_modules/soap/lib/wsdl.js:328:66)
    at [object Object].postProcess (node_modules/soap/lib/wsdl.js:361:17)
    at [object Object].postProcess (node_modules/soap/lib/wsdl.js:377:15)
    at [object Object].postProcess (node_modules/soap/lib/wsdl.js:390:14)
    at [object Object].postProcess (node_modules/soap/lib/wsdl.js:422:21)
    at node_modules/soap/lib/wsdl.js:555:36
    at [object Object].processIncludes (node_modules/soap/lib/wsdl.js:597:9)
    at Array.1 (node_modules/soap/lib/wsdl.js:550:14)
    at EventEmitter._tickCallback (node.js:192:40)

(That was by running a simple soap.createClient with the given URL.)

**Comment by v4l3r10** [comment]
+1! same problem of turbogeek with Oracle-WebLogic
