### ISSUE TITLE
TypeError: Cannot read property 'elements' of undefined

### ISSUE THREAD

**Issue by Fulviuus** [vpulim/node-soap#527]
Hi guys,

I am trying to create a client with node-soap to connect to an existing soap server, but after loading my (local) wsdl file I get this error:

```
/home/fulviov/test-server/node_modules/soap/lib/wsdl.js:468
    this.element = schema.elements[nsName.name];
                         ^
TypeError: Cannot read property 'elements' of undefined
    at MessageElement.postProcess (/home/fulviov/test-server/node_modules/soap/lib/wsdl.js:468:26)
    at OperationElement.postProcess (/home/fulviov/test-server/node_modules/soap/lib/wsdl.js:626:13)
    at PortTypeElement.postProcess (/home/fulviov/test-server/node_modules/soap/lib/wsdl.js:646:11)
    at BindingElement.postProcess (/home/fulviov/test-server/node_modules/soap/lib/wsdl.js:660:14)
    at ServiceElement.postProcess (/home/fulviov/test-server/node_modules/soap/lib/wsdl.js:695:15)
    at /home/fulviov/test-server/node_modules/soap/lib/wsdl.js:989:26
    at /home/fulviov/test-server/node_modules/soap/lib/wsdl.js:1079:7
    at WSDL._processNextInclude (/home/fulviov/test-server/node_modules/soap/lib/wsdl.js:1063:12)
    at null.callback (/home/fulviov/test-server/node_modules/soap/lib/wsdl.js:1078:10)
    at /home/fulviov/test-server/node_modules/soap/lib/wsdl.js:1024:12
```

This is the wsdl I am using: http://pastebin.com/1jsggr30
And this is the xsd: http://pastebin.com/Q62dt13i

I have tried to troubleshoot it, but so far I have not been able to fix it.
Any help would be greatly appreciated!

**Comment by chenxisg** [comment]
I met similar problem, add the below block of code above line 486 will fix the issue. 
if (schema == undefined) {
   return;
}

will fix that issue
