### ISSUE TITLE
Exception when running under node.js 0.12.0

### ISSUE THREAD

**Issue by joviol** [vpulim/node-soap#567]
Hello,

I have updated node to 0.12.0 and now the soap client I wrote doesn't work anymore.
I get the following call stack:
/Volumes/SOURCE/node/poste_test/node_modules/soap/lib/wsdl.js:872
        elem.targetNSAlias = type.namespace;
                           ^
TypeError: Cannot assign to read only property 'targetNSAlias' of CEResultResType|xsd:string|I,W,E
    at ElementElement.description (/Volumes/SOURCE/node/poste_test/node_modules/soap/lib/wsdl.js:872:28)
    at AllElement.description.SequenceElement.description [as description] (/Volumes/SOURCE/node/poste_test/node_modules/soap/lib/wsdl.js:911:29)
    at ComplexTypeElement.description (/Volumes/SOURCE/node/poste_test/node_modules/soap/lib/wsdl.js:814:20)
    at ElementElement.description (/Volumes/SOURCE/node/poste_test/node_modules/soap/lib/wsdl.js:870:46)
    at AllElement.description.SequenceElement.description [as description] (/Volumes/SOURCE/node/poste_test/node_modules/soap/lib/wsdl.js:911:29)
    at ComplexTypeElement.description (/Volumes/SOURCE/node/poste_test/node_modules/soap/lib/wsdl.js:814:20)
    at ElementElement.description (/Volumes/SOURCE/node/poste_test/node_modules/soap/lib/wsdl.js:870:46)
    at AllElement.description.SequenceElement.description [as description] (/Volumes/SOURCE/node/poste_test/node_modules/soap/lib/wsdl.js:911:29)
    at ComplexTypeElement.description (/Volumes/SOURCE/node/poste_test/node_modules/soap/lib/wsdl.js:814:20)
    at ElementElement.description (/Volumes/SOURCE/node/poste_test/node_modules/soap/lib/wsdl.js:896:31)

Please let me know if you need more details.
Thank You

**Comment by herom** [comment]
Seems related to #550 and the suggestions/track down that @andrewbranch made. It would be super awesome if someone could take on this and provide a PR which makes `node-soap` `node v0.12` compliant :+1:

**Comment by herom** [comment]
P.S.: Closing in favour of #550 as I'd like to keep these problems in one place instead of cluttered all over our issues :smiley: - thanks for opening this issue and the provided details :+1:
