### ISSUE TITLE
More Specific Information On Modifing XML

### ISSUE THREAD

**Issue by Zenitram-Oriaj** [vpulim/node-soap#647]
Need some help please:

I need to change this (which is what node-soap creates):

```
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns:tns="http://schemas.novell.com/2005/01/GroupWise/groupwise.wsdl" xmlns:types="http://schemas.novell.com/2005/01/GroupWise/types"
               xmlns:methods="http://schemas.novell.com/2005/01/GroupWise/methods" xmlns:events="http://schemas.novell.com/2005/01/GroupWise/events">
  <soap:Body>
    <methods:loginRequest xmlns:methods="http://schemas.novell.com/2005/01/GroupWise/methods"
                          xmlns="http://schemas.novell.com/2005/01/GroupWise/methods">
      <methods:auth>
        <methods:username>ao</methods:username>
        <methods:password>!boi123</methods:password>
      </methods:auth>
      <methods:language>en</methods:language>
      <methods:version>1.05</methods:version>
      <methods:userid>true</methods:userid>
    </methods:loginRequest>
  </soap:Body>
</soap:Envelope>

```

...to look more like this (is what a sample c# program that was provided had created):

```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<soap:Body>
  <loginRequest xmlns="http://schemas.novell.com/2005/01/GroupWise/methods">
    <auth xmlns:q1="http://schemas.novell.com/2005/01/GroupWise/types" xsi:type="q1:PlainText">
      <q1:username>ao</q1:username>
      <q1:password>!boi123</q1:password>
    </auth>
    <language>en</language>
    <version>1.05</version>
    <userid>true</userid>
  </loginRequest>
</soap:Body>
</soap:Envelope>

```

I intercepted the node-soap generated xml and replace it for the corrected xml and i was able to login just fine where as the node-soap generated xml comes back with an error from the server that indicates, in a basic since, that the request is improperly formatted.

Now I pretty sure that "methods" is the equivalent to "q1" but it is not on every tag in the second version.

I think I need to modify my 'wsdlOptions', I just don't know how.

Please help anyone and thanks in advance.

**Comment by pentode** [comment]
Hi,

  Can you test if the xml below will work for you?  I suspect this might be another case where node-soap just isn't handling the xsi:type attribute, so I've added that to the methods:auth element.  It also looks like node-soap is generating unnecessary xmlns attributes (on loginRequest)...but I'm no SOAP expert.  I may have some time over the next couple of days to improve node-soap's xsi:type handling, so if you can let me know if the xml below works, I'll try to coerce node-soap to generate that.  Also, it would be helpful if you could give me a snippet of javascript that you're using to generate the web service call.

  BTW, q1 in your example is the xmlns for the "types" schema.  Where that appears in the xsi:type attribute (q1:PlainText) on the auth element it means that element's content is the PlainText type from the q1 (types) schema and the inner elements also need to reference that xmlns so their type can be determined.

```
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns:tns="http://schemas.novell.com/2005/01/GroupWise/groupwise.wsdl" xmlns:types="http://schemas.novell.com/2005/01/GroupWise/types"
               xmlns:methods="http://schemas.novell.com/2005/01/GroupWise/methods" xmlns:events="http://schemas.novell.com/2005/01/GroupWise/events">
  <soap:Body>
    <methods:loginRequest>
      <methods:auth xsi:type="types:PlainText">
        <types:username>ao</types:username>
        <types:password>!boi123</types:password>
      </methods:auth>
      <methods:language>en</methods:language>
      <methods:version>1.05</methods:version>
      <methods:userid>true</methods:userid>
    </methods:loginRequest>
  </soap:Body>
</soap:Envelope>
```

**Comment by Zenitram-Oriaj** [comment]
pentode:
Thank you for responding. I too am not any kind of SOAP expert
I input the suggested xml and this was the result:
```
/Users/digimenet/Desktop/soapTester/node_modules/soap/lib/client.js:291
      result = obj.Body[output.$name];
                       ^
TypeError: Cannot read property 'loginResponse' of undefined
    at /Users/digimenet/Desktop/soapTester/node_modules/soap/lib/client.js:291:24
    at Request._callback (/Users/digimenet/Desktop/soapTester/node_modules/soap/lib/http.js:69:7)
    at Request.self.callback (/Users/digimenet/Desktop/soapTester/node_modules/soap/node_modules/request/request.js:368:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/digimenet/Desktop/soapTester/node_modules/soap/node_modules/request/request.js:1219:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/digimenet/Desktop/soapTester/node_modules/soap/node_modules/request/request.js:1167:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```
Any help you can provide will be awesome. 
Here is a basic node app I am using:
```
var soap = require('soap');
var path = require('path');

var url = path.join(__dirname, './wsdl/groupwise.wsdl');
var client = {};

function init(cb) {
	soap.createClient(url, function (err, c) {
		if (err) {
			cb(err, null);
		} else {
			cb(null, c);
		}
	});
}

init(function (err, c) {
	if (err) {
		console.error('---------INIT ERROR----------');
		console.error(err);
	} else {
		client = c;
        client.wsdl.uri = 'http://boi.selfip.com:7191/soap'; // DOES NOT WORK!!!
		var args = {
			auth:     {
				username: 'ao',
				password: '!boi123'
			},
			language: 'en',
			version:  '1.05',
			userid:   true
		};

		console.log('---------INIT RESULT----------');

		client.loginRequest(args, function (err, res) {
			if (err) {
				console.error(err);
			} else {
				console.log(res);
			}
		});
	}
});
```
(NOTE: I had to manually add the location in the client.js lib as it was not excepting  client.wsdl.uri = 'http://boi.selfip.com:7191/soap')

If you would like to try your own experimenting, you can access this SOAP Service by going to:
http://boi.selfip.com:7191/soap
(Note: Sending a simple GET to this should return something like this: 
HTTP/1.1 200 Date: Wed, 06 May 2015 16:16:08 GMT Server: Windows GroupWise POA 14.0.0 Content-Type: text/xml; charset=utf-8 Pragma: no-cache 
)

And the WSDL docs are available here:
https://www.dropbox.com/sh/td5iil3qb2k07tm/AABvhEO4EffLOKzh1IIZ4k0Ea?dl=0
(Note: the gws.wsdl file is a compiled version in where I imported the external xsd files. The folder called "Pre-Compiled" contains the original files. So use either.)

Once again, thank you again and any help would be great. But if you can get to it or resolve it, that's ok to.

**Comment by Zenitram-Oriaj** [comment]
I probably should have added a success return result, which should something like this:
```
{ session: 'LEamUbNrihcTNaub',
  userinfo: 
   { name: 'Agile Office',
     email: 'ao@diginet.local',
     uuid: '80121DB0-0383-0000-BE64-696734326237',
     userid: 'ao',
     domain: 'diginet',
     postOffice: 'poa',
     fid: 'upx' },
  gwVersion: '14.0.0',
  build: '115243',
  serverUTCTime: Wed May 06 2015 09:35:41 GMT-0700 (PDT),
  status: { code: 0 } }
```

**Comment by pentode** [comment]
Sorry I wasn't clear...I wanted you to test the xml I supplied as input to the web service (not to node-soap).  I've just done that using curl and confirmed that the web service responds as expected to the xml node-soap generates with the following modification (to add xsi:type and to correct the ns for the enclosed elements.

What this means is that I think it will be fairly straightfoward to add support for xsi:type attribute to the methods:auth element; the information is collected when parsing the wsdl, but just isn't used right now.  I may have some time over the next couple of days to add this feature...er, fix this bug/limitation.

```
<methods:auth xsi:type="types:PlainText">
        <types:username>ao</types:username>
        <types:password>!boi123</types:password>
      </methods:auth>
```


`sh$ curl -i --header "Content-Type: text/xml;charset=UTF-8" --header "SOAPAction: loginRequest" --data @x.xml http://boi.selfip.com:7191/soap`

content of x.xml
```
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns:tns="http://schemas.novell.com/2005/01/GroupWise/groupwise.wsdl" xmlns:types="http://schemas.novell.com/2005/01/GroupWise/types"
               xmlns:methods="http://schemas.novell.com/2005/01/GroupWise/methods" xmlns:events="http://schemas.novell.com/2005/01/GroupWise/events">
  <soap:Body>
    <methods:loginRequest xmlns:methods="http://schemas.novell.com/2005/01/GroupWise/methods"
                          xmlns="http://schemas.novell.com/2005/01/GroupWise/methods">
      <methods:auth xsi:type="types:PlainText">
        <types:username>ao</types:username>
        <types:password>!boi123</types:password>
      </methods:auth>
      <methods:language>en</methods:language>
      <methods:version>1.05</methods:version>
      <methods:userid>true</methods:userid>
    </methods:loginRequest>
  </soap:Body>
</soap:Envelope>
```

**Comment by Zenitram-Oriaj** [comment]
I tried what you did and it return what it was suppose to do:
```
<?xml version="1.0" encoding="UTF-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.novell.com/2005/01/GroupWise/methods" xmlns:gwt="http://schemas.novell.com/2005/01/GroupWise/types"><s:Header/><s:Body><loginResponse><gwm:session>x2PhNQ8DNd05_mCo</gwm:session><gwm:userinfo><gwt:name>Agile Office</gwt:name><gwt:email>ao@diginet.local</gwt:email><gwt:uuid>80121DB0-0383-0000-BE64-696734326237</gwt:uuid><gwt:userid>ao</gwt:userid><gwt:domain>diginet</gwt:domain><gwt:postOffice>poa</gwt:postOffice><gwt:fid>upx</gwt:fid></gwm:userinfo><gwm:gwVersion>14.0.0 </gwm:gwVersion><gwm:build>115243</gwm:build><gwm:serverUTCTime>2015-05-06T17:37:32Z</gwm:serverUTCTime><status><gwt:code>0</gwt:code></status></loginResponse></s:Body></s:Envelope>
```

Thank you for your help. If you are able to add this feature and/or fix this bug, that would be great. I will have this service running for the next several weeks so feel free to test against it if you like. If you need anything from me, don't hesitate to ask. I am more than happy to assist wherever I can.

**Comment by pentode** [comment]
This may already be supported based on a quick read of the relevant bits in WSDL.objectToXML().

Sorry, I don't have time to test this at the moment, but could you try passing your auth object with a $type property as shown below, which references the "types" ns and the "PlainText" type as required by the web service.

```
auth:     {
                $type: "types:PlainText",
                username: 'ao',
                password: '!boi123'
            },
```

**Comment by Zenitram-Oriaj** [comment]
So this is what the node-soap module generated:
```
<methods:loginRequest xmlns:methods="http://schemas.novell.com/2005/01/GroupWise/methods" xmlns="http://schemas.novell.com/2005/01/GroupWise/methods">
  <methods:auth>
    <methods:$type>types:PlainText</methods:$type>
    <methods:username>ao</methods:username>
    <methods:password>!boi123</methods:password>
  </methods:auth>
  <methods:language>en</methods:language>
  <methods:version>1.05</methods:version>
  <methods:userid>true</methods:userid>
</methods:loginRequest>

```
Thanks.

**Comment by Zenitram-Oriaj** [comment]
So, I found a temporary solution to get around this issue:
```
var soap = require('soap');
var path = require('path');

var url = path.join(__dirname, './wsdl/groupwise.wsdl');
var client = {};

function init(cb) {
	soap.createClient(url, function (err, c) {
		if (err) {
			cb(err, null);
		} else {
			cb(null, c);
		}
	});
}

init(function (err, c) {
	if (err) {
		console.error('---------INIT ERROR----------');
		console.error(err);
	} else {
		client = c;
		client.setEndpoint('http://boi.selfip.com:7191/soap');
		//console.log(client);
		var args =
			'<loginRequest xmlns="http://schemas.novell.com/2005/01/GroupWise/methods">' +
			'<auth xmlns:q1="http://schemas.novell.com/2005/01/GroupWise/types" xsi:type="q1:PlainText">' +
			'<q1:username>ao</q1:username>' +
			'<q1:password>!boi123</q1:password>' +
			'</auth>' +
			'<language>en</language>' +
			'<version>1.05</version>' +
			'<userid>true</userid>' +
			'</loginRequest>';

		console.log('---------INIT RESULT----------');
		client.loginRequest(args, function (err, res) {
			if (err) {
				console.error(err);
			} else {
				console.log(res);
			}
		});
	}
});

```
So what I have done is that instead of passing the "args" as an OBJECT, I passed it as a STRING.  
This seems to work fine. Below 

```
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns:methods="http://schemas.novell.com/2005/01/GroupWise/methods" xmlns:tns="http://schemas.novell.com/2005/01/GroupWise/groupwise.wsdl" xmlns:types="http://schemas.novell.com/2005/01/GroupWise/types" xmlns:events="http://schemas.novell.com/2005/01/GroupWise/events"><soap:Body><loginRequest xmlns="http://schemas.novell.com/2005/01/GroupWise/methods"><auth xmlns:q1="http://schemas.novell.com/2005/01/GroupWise/types" xsi:type="q1:PlainText"><q1:username>ao</q1:username><q1:password>!boi123</q1:password></auth><language>en</language><version>1.05</version><userid>true</userid></loginRequest></soap:Body></soap:Envelope>
```
This, of course, is only the first step. I will now need to try other soap methods and see if I can get it to work. One of the task will see how the addSoapHeader will work with the "session key" that is generated by the loginRequest.

Thanks for your help. Let me know if there are things you would like me to try.

**Comment by pentode** [comment]
Ok, after reading the code more closely, I see that the "attributes" property of the (auth) object can be used to specify the xsi:type of the content.  I've just verified that the following works with the web service endpoint you provided.

```
auth:     {
          attributes: {
            'xsi_type': {
              xmlns: 'types',
              type: 'PlainText'
            }
          },
          username: 'ao',
          password: '!boi123'
        },
```

Also, to specify the endpoint to your web service, you need to do that in the createClient() call, e.g.,

```
var clOpts =  {endpoint: 'http://boi.selfip.com:7191/soap', strict: true};
var client = soap.createClient(wsdl, clOpts, function(err, client) {
  ...
}
```
