### ISSUE TITLE
TypeError: Cannot set property 'targetNSAlias' of undefined

### ISSUE THREAD

**Issue by andrewkro** [vpulim/node-soap#68]
Hey Guys,

After finally getting expat compiled and installed on windows, i've tried loading a wsdl into node-soap to create a web service server.

Ive loaded into SoapUI tool to test wsdl/xsd compliance and sent test request/response ok.

when i start a simple node http server, i get the following:

C:\Documents and Settings\Administrator\My Documents\Web Service Current\node_modules\soap\lib\wsdl.js:346
        this.element.targetNSAlias = ns;
                                   ^
TypeError: Cannot set property 'targetNSAlias' of undefined
    at [object Object].postProcess (C:\Documents and Settings\Administrator\My Documents\Web Service Current\node_modules\soap\lib\wsdl.js:346:36)
    at [object Object].postProcess (C:\Documents and Settings\Administrator\My Documents\Web Service Current\node_modules\soap\lib\wsdl.js:378:17)
    at [object Object].postProcess (C:\Documents and Settings\Administrator\My Documents\Web Service Current\node_modules\soap\lib\wsdl.js:395:15)
    at [object Object].postProcess (C:\Documents and Settings\Administrator\My Documents\Web Service Current\node_modules\soap\lib\wsdl.js:408:14)
    at [object Object].postProcess (C:\Documents and Settings\Administrator\My Documents\Web Service Current\node_modules\soap\lib\wsdl.js:440:21)
    at C:\Documents and Settings\Administrator\My Documents\Web Service Current\node_modules\soap\lib\wsdl.js:594:36
    at C:\Documents and Settings\Administrator\My Documents\Web Service Current\node_modules\soap\lib\wsdl.js:641:13
    at C:\Documents and Settings\Administrator\My Documents\Web Service Current\node_modules\soap\lib\wsdl.js:641:13
    at [object Object]._processNextInclude (C:\Documents and Settings\Administrator\My Documents\Web Service Current\node_modules\soap\lib\wsdl.js:635:26)
    at [object Object].callback (C:\Documents and Settings\Administrator\My Documents\Web Service Current\node_modules\soap\lib\wsdl.js:640:14)

The WSDL being loaded is here: http://pastebin.com/iECgpUJs
The first import schema which is loaded (aidx/IATA_AIDX_FlightLegNotifRQ.xsd) is here: http://pastebin.com/5V0r3eYM

Any help would be greatly appreciated!

Andrew

**Comment by andrewbranch** [comment]
@Himanshu4, are you going to submit a pull request? It’d be nice to see some progress here.

**Comment by Himanshu4** [comment]
I have submitted a new pull request for the same issue.

**Comment by herom** [comment]
Since @Himanshu4 s PR is merged in now, this should be solved.
