### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by anupamasajja** [vpulim/node-soap#718]
I am getting the following error when trying to consume wsdl 

/home/dc-user/myproject/node_modules/soap/lib/wsdl.js:720
for (var i = 0, child; child = children[i]; i++) {
                                       ^

TypeError: Cannot read property '0' of undefined
    at ServiceElement.postProcess (/home/dc-user/myproject/node_modules/soap/lib/wsdl.js:720:40)
    at /home/dc-user/myproject/node_modules/soap/lib/wsdl.js:1035:26
    at /home/dc-user/myproject/node_modules/soap/lib/wsdl.js:1134:7
    at /home/dc-user/myproject/node_modules/soap/lib/wsdl.js:1134:7
    at /home/dc-user/myproject/node_modules/soap/lib/wsdl.js:1134:7
    at WSDL._processNextInclude (/home/dc-user/myproject/node_modules/soap/lib/wsdl.js:1115:12)
    at null.callback (/home/dc-user/myproject/node_modules/soap/lib/wsdl.js:1133:10)
    at /home/dc-user/myproject/node_modules/soap/lib/wsdl.js:1070:12
    at /home/dc-user/myproject/node_modules/soap/lib/wsdl.js:1134:7
    at /home/dc-user/myproject/node_modules/soap/lib/wsdl.js:1134:7

**Comment by anupamasajja** [comment]
At wsdl.js: 720 I tried to put in
if(!children) {
return;
}
then I am getting a different error message. It was not able to identify functions that are available for me to consume
client.describe does not give any functions.

**Comment by herom** [comment]
hard to say what's causing the issue/error without the WSDL itself (please, shorten if possible!).

**Comment by jsdevel** [comment]
Closing for lack of activity.  Please open a PR with a fix if there is a defect.
