### ISSUE TITLE
request is undefined?

### ISSUE THREAD

**Issue by ashic** [vpulim/node-soap#736]
Hello,
Apologies for the noobness, but I'm having trouble getting started. Here's my index.js:

```
var express = require('express');
var soap = require('soap');

var wsdlUrl = 'http://www.w3schools.com/webservices/tempconvert.asmx?WSDL';

soap.createClient(wsdlUrl, function(err, client) {
      console.log(err);
  });


app.get('/', function(req, res){
    res.send('hello world!!');
});

var server = app.listen(3000, function(){
    var host = server.address().address;
    var port = server.address().port;

    console.log("example app listening on http://%s:%s", host, port);
});
```

Here's the package.json:

```
{
  "name": "first",
  "version": "1.0.0",
  "description": "something something",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.13.3",
    "soap": "^0.9.4"
  }
}
```

When I run node index.js, I get these errors:

```
[Error: Invalid protocol: null]
D:\nodesandbox\first\node_modules\soap\node_modules\request\request.js:793
  self.req = self.httpModule.request(reqOptions)
                            ^
TypeError: Cannot read property 'request' of undefined
    at Request.start (D:\nodesandbox\first\node_modules\soap\node_modules\request\request.js:793:29)
    at Request.end (D:\nodesandbox\first\node_modules\soap\node_modules\request\request.js:1394:10)
    at HttpClient.request (D:\nodesandbox\first\node_modules\soap\lib\http.js:112:9)
    at open_wsdl (D:\nodesandbox\first\node_modules\soap\lib\wsdl.js:1903:16)
    at _requestWSDL (D:\nodesandbox\first\node_modules\soap\lib\soap.js:32:5)
    at Object.createClient (D:\nodesandbox\first\node_modules\soap\lib\soap.js:49:3)
    at Object.<anonymous> (D:\nodesandbox\first\index.js:6:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

Would appreciate any pointers to get this running.

**Comment by jsdevel** [comment]
My guess is that your WSDL URL had an invalid protocol.

**Comment by jsdevel** [comment]
I tried your script and it works just fine.

**Comment by ashic** [comment]
Yup...tried it at home. I think work network is blocking some stuff coming down, and things are failing silently. Thanks for testing.
